#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'parts', 'ad711.json');
const svgPath = path.join(root, 'parts', 'ad711.svg');
const part = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const pinOrder = ['offset_1', 'inn', 'inp', 'vneg', 'offset_5', 'out', 'vpos', 'nc'];

assert.equal(part.kind, 'ad711');
assert.deepEqual(part.terminals.map(({name}) => name), pinOrder,
  'terminal array is the Analog Devices N-8 PDIP physical pin order');
assert.ok(part.terminals.every(({functions}) => Array.isArray(functions) && functions.length === 0));
for (let pin = 1; pin <= 8; pin++) {
  const name = pinOrder[pin - 1];
  const left = pin <= 4;
  assert.deepEqual(part.footprint.leads[name], {
    dRow: left ? 0 : 5,
    dCol: left ? pin - 1 : 8 - pin,
  }, `physical pin ${pin} (${name}) occupies its real breadboard column`);
}
assert.equal(part.footprint.straddlesGutter, true);
assert.equal(part.footprint.minCols, 4);
assert.match(part._note, /AD711JNZ N-8 plastic PDIP/);
assert.match(part._note, /RN-8 SOIC.*must not borrow this face/);

const svg = fs.readFileSync(svgPath, 'utf8');
assert.match(svg, /AD711 — 8-pin DIP, generated by generate-dip-art\.js from ad711\.json/);
assert.match(svg, />AD711</);
for (const name of pinOrder) assert.match(svg, new RegExp(`>${name}<`));

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'bw-parts-ad711-'));
try {
  fs.mkdirSync(path.join(temp, 'parts'));
  fs.copyFileSync(path.join(root, 'generate-dip-art.js'), path.join(temp, 'generate-dip-art.js'));
  fs.copyFileSync(jsonPath, path.join(temp, 'parts', 'ad711.json'));
  execFileSync(process.execPath, ['generate-dip-art.js', 'ad711'], {cwd: temp, stdio: 'pipe'});
  assert.equal(fs.readFileSync(path.join(temp, 'parts', 'ad711.svg'), 'utf8'), svg,
    'committed AD711 art is exactly generator-owned');
} finally {
  fs.rmSync(temp, {recursive: true, force: true});
}

const ratings = JSON.parse(fs.readFileSync(path.join(root, 'current-ratings.json'), 'utf8'));
assert.deepEqual(ratings.ad711, {
  _src: 'Analog Devices AD711 Rev. E: J-grade quiescent current 3.4mA max',
  chip_mA: 0,
  supply_mA: 3.4,
});
console.log('AD711 N-8 PDIP pinout, package boundary, generated art, footprint, and supply budget verified.');
