#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'parts', 'lm324.json');
const svgPath = path.join(root, 'parts', 'lm324.svg');
const part = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const pinOrder = [
  '1_out', '1_neg', '1_pos', 'vcc', '2_pos', '2_neg', '2_out',
  '3_out', '3_neg', '3_pos', 'gnd', '4_pos', '4_neg', '4_out',
];

assert.equal(part.kind, 'lm324');
assert.deepEqual(part.terminals.map(({name}) => name), pinOrder,
  'terminal array is the TI PDIP-14 physical pin order');
assert.ok(part.terminals.every(({functions}) => Array.isArray(functions) && functions.length === 0));
for (let pin = 1; pin <= 14; pin++) {
  const name = pinOrder[pin - 1];
  const lead = part.footprint.leads[name];
  const left = pin <= 7;
  assert.deepEqual(lead, {
    dRow: left ? 0 : 5,
    dCol: left ? pin - 1 : 14 - pin,
  }, `physical pin ${pin} (${name}) occupies its real breadboard column`);
}

const svg = fs.readFileSync(svgPath, 'utf8');
assert.match(svg, /LM324 — 14-pin DIP, generated by generate-dip-art\.js from lm324\.json/);
assert.match(svg, />QUAD OP AMP</);
for (const name of pinOrder) assert.match(svg, new RegExp(`>${name}<`));

// Re-run the real generator in isolation and require byte identity. This is a
// generation proof without rewriting the tracked checkout during npm test.
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'bw-parts-lm324-'));
try {
  fs.mkdirSync(path.join(temp, 'parts'));
  fs.copyFileSync(path.join(root, 'generate-dip-art.js'), path.join(temp, 'generate-dip-art.js'));
  fs.copyFileSync(jsonPath, path.join(temp, 'parts', 'lm324.json'));
  execFileSync(process.execPath, ['generate-dip-art.js', 'lm324'], {cwd: temp, stdio: 'pipe'});
  assert.equal(fs.readFileSync(path.join(temp, 'parts', 'lm324.svg'), 'utf8'), svg,
    'committed LM324 art is exactly generator-owned');
} finally {
  fs.rmSync(temp, {recursive: true, force: true});
}

const ratings = JSON.parse(fs.readFileSync(path.join(root, 'current-ratings.json'), 'utf8'));
assert.deepEqual(ratings.lm324, {
  _src: 'TI LM324 SLOS066AE: conservative 3mA whole-package supply budget',
  chip_mA: 0,
  supply_mA: 3,
});
console.log('LM324 PDIP-14 pinout, generated art, footprint, and supply budget verified.');
