#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'parts', 'lm741.json');
const svgPath = path.join(root, 'parts', 'lm741.svg');
const part = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const pinOrder = ['offset_1', 'inn', 'inp', 'vneg', 'offset_5', 'out', 'vpos', 'nc'];

assert.equal(part.kind, 'lm741');
assert.deepEqual(part.terminals.map(({name}) => name), pinOrder,
  'terminal array is the TI PDIP-8 physical pin order');
assert.ok(part.terminals.every(({functions}) => Array.isArray(functions) && functions.length === 0));
for (let pin = 1; pin <= 8; pin++) {
  const name = pinOrder[pin - 1];
  const left = pin <= 4;
  assert.deepEqual(part.footprint.leads[name], {
    dRow: left ? 0 : 5,
    dCol: left ? pin - 1 : 8 - pin,
  }, `physical pin ${pin} (${name}) occupies its real breadboard column`);
}

const svg = fs.readFileSync(svgPath, 'utf8');
assert.match(svg, /LM741 — 8-pin DIP, generated by generate-dip-art\.js from lm741\.json/);
assert.match(svg, />SINGLE OP AMP</);
for (const name of pinOrder) assert.match(svg, new RegExp(`>${name}<`));

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'bw-parts-lm741-'));
try {
  fs.mkdirSync(path.join(temp, 'parts'));
  fs.copyFileSync(path.join(root, 'generate-dip-art.js'), path.join(temp, 'generate-dip-art.js'));
  fs.copyFileSync(jsonPath, path.join(temp, 'parts', 'lm741.json'));
  execFileSync(process.execPath, ['generate-dip-art.js', 'lm741'], {cwd: temp, stdio: 'pipe'});
  assert.equal(fs.readFileSync(path.join(temp, 'parts', 'lm741.svg'), 'utf8'), svg,
    'committed LM741 art is exactly generator-owned');
} finally {
  fs.rmSync(temp, {recursive: true, force: true});
}

const ratings = JSON.parse(fs.readFileSync(path.join(root, 'current-ratings.json'), 'utf8'));
assert.deepEqual(ratings.lm741, {
  _src: 'TI LM741 SNOSC25D: Icc max 2.8mA',
  chip_mA: 0,
  supply_mA: 2.8,
});
console.log('LM741 PDIP-8 pinout, generated art, footprint, and maximum supply budget verified.');
