#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'parts', 'lt1014.json');
const svgPath = path.join(root, 'parts', 'lt1014.svg');
const part = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const pinOrder = [
  '1_out', '1_neg', '1_pos', 'vpos', '2_pos', '2_neg', '2_out',
  '3_out', '3_neg', '3_pos', 'vneg', '4_pos', '4_neg', '4_out',
];

assert.equal(part.kind, 'lt1014');
assert.deepEqual(part.terminals.map(({name}) => name), pinOrder,
  'terminal array is the LT1014 N/J 14-pin physical order');
for (let pin = 1; pin <= 14; pin++) {
  const name = pinOrder[pin - 1];
  const left = pin <= 7;
  assert.deepEqual(part.footprint.leads[name], {
    dRow: left ? 0 : 5,
    dCol: left ? pin - 1 : 14 - pin,
  }, `physical pin ${pin} (${name}) occupies its real breadboard column`);
}

const svg = fs.readFileSync(svgPath, 'utf8');
assert.match(svg, /LT1014 — 14-pin DIP, generated by generate-dip-art\.js from lt1014\.json/);
assert.match(svg, />PRECISION QUAD</);
for (const name of pinOrder) assert.match(svg, new RegExp(`>${name}<`));

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'bw-parts-lt1014-'));
try {
  fs.mkdirSync(path.join(temp, 'parts'));
  fs.copyFileSync(path.join(root, 'generate-dip-art.js'), path.join(temp, 'generate-dip-art.js'));
  fs.copyFileSync(jsonPath, path.join(temp, 'parts', 'lt1014.json'));
  execFileSync(process.execPath, ['generate-dip-art.js', 'lt1014'], {cwd: temp, stdio: 'pipe'});
  assert.equal(fs.readFileSync(path.join(temp, 'parts', 'lt1014.svg'), 'utf8'), svg,
    'committed LT1014 art is exactly generator-owned');
} finally {
  fs.rmSync(temp, {recursive: true, force: true});
}

const ratings = JSON.parse(fs.readFileSync(path.join(root, 'current-ratings.json'), 'utf8'));
assert.deepEqual(ratings.lt1014, {
  _src: 'TI LT1014 SLOS039D: 0.55mA max per amplifier at 25C, 2.2mA whole package',
  chip_mA: 0,
  supply_mA: 2.2,
});
console.log('LT1014 PDIP-14 pinout, generated art, footprint, and supply budget verified.');
