#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'parts', 'op27.json');
const svgPath = path.join(root, 'parts', 'op27.svg');
const part = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const pinOrder = ['offset_1', 'inn', 'inp', 'vneg', 'offset_5', 'out', 'vpos', 'nc'];

assert.equal(part.kind, 'op27');
assert.deepEqual(part.terminals.map(({name}) => name), pinOrder,
  'terminal array is the Analog Devices P-suffix PDIP-8 physical pin order');
assert.match(part._note, /SOIC and J-suffix TO-99 imports must not acquire this breadboard face/);
assert.ok(part.terminals.every(({functions}) => Array.isArray(functions) && functions.length === 0));
for (let pin = 1; pin <= 8; pin++) {
  const name = pinOrder[pin - 1];
  const left = pin <= 4;
  assert.deepEqual(part.footprint.leads[name], {
    dRow: left ? 0 : 5,
    dCol: left ? pin - 1 : 8 - pin,
  }, `physical pin ${pin} (${name}) occupies its real breadboard column`);
}
assert.equal(part.footprint.straddlesGutter, true);
assert.equal(part.footprint.minCols, 4);

const svg = fs.readFileSync(svgPath, 'utf8');
assert.match(svg, /OP27 — 8-pin DIP, generated by generate-dip-art\.js from op27\.json/);
assert.match(svg, />OP27</);
for (const name of pinOrder) assert.match(svg, new RegExp(`>${name}<`));

const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'bw-parts-op27-'));
try {
  fs.mkdirSync(path.join(temp, 'parts'));
  fs.copyFileSync(path.join(root, 'generate-dip-art.js'), path.join(temp, 'generate-dip-art.js'));
  fs.copyFileSync(jsonPath, path.join(temp, 'parts', 'op27.json'));
  execFileSync(process.execPath, ['generate-dip-art.js', 'op27'], {cwd: temp, stdio: 'pipe'});
  assert.equal(fs.readFileSync(path.join(temp, 'parts', 'op27.svg'), 'utf8'), svg,
    'committed OP27 art is exactly generator-owned');
} finally {
  fs.rmSync(temp, {recursive: true, force: true});
}

const ratings = JSON.parse(fs.readFileSync(path.join(root, 'current-ratings.json'), 'utf8'));
assert.deepEqual(ratings.op27, {
  _src: 'Analog Devices OP27 Rev. H Figure 12: conservative 4mA supply budget across the characterized supply range',
  chip_mA: 0,
  supply_mA: 4,
});
console.log('OP27 PDIP-8 pinout, generated art, footprint, package boundary, and supply budget verified.');
