#!/usr/bin/env node
/**
 * generate-dip.js — Parametric DIP IC SVG + JSON sidecar generator.
 *
 * Given a pin-map table (chip kind, pin count, pin names, label),
 * generates bench-style DIP package SVGs and matching JSON sidecars
 * in parts/<kind>.svg and parts/<kind>.json.
 *
 * DIP geometry:
 *   Pin 1 is top-left, numbering goes DOWN the left side then
 *   UP the right side (standard DIP convention).
 *   VCC is typically the top-right pin, GND the bottom-left.
 *
 * Usage: node generate-dip.js          (generates all chips in PIN_MAPS)
 *        node generate-dip.js 74hc00   (generates one chip)
 */

const fs = require('fs');
const path = require('path');

const PARTS_DIR = path.join(__dirname, 'parts');

// ── DIP geometry constants ──────────────────────────────────────────
const PIN_SPACING = 5;       // vertical spacing between pins
const PIN_LENGTH  = 10;      // lead wire length from body edge
const BODY_X      = 10;      // left edge of IC body
const BODY_RX     = 2;       // corner radius
const PAD_R       = 1.5;     // terminal pad radius
const PIN_STROKE  = 1.5;
const NOTCH_R     = 3;       // notch semicircle radius
const DOT_R       = 1.5;    // pin-1 dot radius

function dipGeometry(pinCount) {
  const half = pinCount / 2;
  const bodyH = (half - 1) * PIN_SPACING + 12;  // padding top/bottom
  const bodyW = pinCount > 20 ? 60 : 50;        // wider body for DIP-40+
  const svgW  = bodyW + 2 * BODY_X;
  const svgH  = bodyH + 4;  // small margin
  const bodyY = 2;
  return { half, bodyH, bodyW, svgW, svgH, bodyY };
}

function pinY(index, half, bodyY) {
  // index 0 = pin 1 (top-left), index half-1 = bottom-left
  const topPad = 6;
  return bodyY + topPad + index * PIN_SPACING;
}

// ── SVG generation ──────────────────────────────────────────────────
function generateSvg(chip) {
  const { kind, pinCount, pins, label, sublabel } = chip;
  const { half, bodyH, bodyW, svgW, svgH, bodyY } = dipGeometry(pinCount);
  const bodyRight = BODY_X + bodyW;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${svgW} ${svgH}" width="${svgW}" height="${svgH}">\n`;
  svg += `  <!-- ${label} — ${pinCount}-pin DIP, generated by generate-dip.js -->\n`;

  // Body
  svg += `  <rect x="${BODY_X}" y="${bodyY}" width="${bodyW}" height="${bodyH}" rx="${BODY_RX}" fill="#303030" stroke="#1a1a1a" stroke-width="1"/>\n`;

  // Notch at top center
  const notchCx = BODY_X + bodyW / 2;
  svg += `  <path d="M${notchCx - NOTCH_R} ${bodyY} A${NOTCH_R} ${NOTCH_R} 0 0 1 ${notchCx + NOTCH_R} ${bodyY}" fill="#303030" stroke="#555" stroke-width="0.8"/>\n`;

  // Pin 1 dot
  const dotX = BODY_X + 5;
  const dotY = bodyY + 5;
  svg += `  <circle cx="${dotX}" cy="${dotY}" r="${DOT_R}" fill="#b0b0b0"/>\n`;

  // Label
  const labelY = bodyY + bodyH / 2 - 1;
  svg += `  <text x="${BODY_X + bodyW / 2}" y="${labelY}" text-anchor="middle" font-family="monospace" font-size="5.5" fill="#c0c0c0">${label}</text>\n`;
  if (sublabel) {
    svg += `  <text x="${BODY_X + bodyW / 2}" y="${labelY + 8}" text-anchor="middle" font-family="monospace" font-size="3.5" fill="#888">${sublabel}</text>\n`;
  }

  // Pins — left side (pin 1 to pin half)
  for (let i = 0; i < half; i++) {
    const py = pinY(i, half, bodyY);
    const pinNum = i + 1;
    const pinName = pins[i] || `p${pinNum}`;
    // Lead wire
    svg += `  <line x1="0" y1="${py}" x2="${BODY_X}" y2="${py}" stroke="#aaa" stroke-width="${PIN_STROKE}" stroke-linecap="round"/>\n`;
    // Pad
    svg += `  <circle cx="0" cy="${py}" r="${PAD_R}" fill="#c0c0c0"/>\n`;
    // Pin label (inside body, near left edge)
    const labelFontSize = pinName.length > 4 ? 2.5 : 3;
    svg += `  <text x="${BODY_X + 3}" y="${py + 1}" font-family="monospace" font-size="${labelFontSize}" fill="#888">${pinName}</text>\n`;
  }

  // Pins — right side (pin pinCount down to pin half+1)
  for (let i = 0; i < half; i++) {
    const py = pinY(half - 1 - i, half, bodyY);  // mirrored: top-right is highest pin number
    const pinNum = half + 1 + i;
    const pinName = pins[pinNum - 1] || `p${pinNum}`;
    // Lead wire
    svg += `  <line x1="${bodyRight}" y1="${py}" x2="${svgW}" y2="${py}" stroke="#aaa" stroke-width="${PIN_STROKE}" stroke-linecap="round"/>\n`;
    // Pad
    svg += `  <circle cx="${svgW}" cy="${py}" r="${PAD_R}" fill="#c0c0c0"/>\n`;
    // Pin label (inside body, near right edge)
    const labelFontSize = pinName.length > 4 ? 2.5 : 3;
    svg += `  <text x="${bodyRight - 3}" y="${py + 1}" text-anchor="end" font-family="monospace" font-size="${labelFontSize}" fill="#888">${pinName}</text>\n`;
  }

  svg += `</svg>\n`;
  return svg;
}

// ── JSON sidecar generation ─────────────────────────────────────────
function generateJson(chip) {
  const { kind, pinCount, pins } = chip;
  const { half, svgW, svgH, bodyY } = dipGeometry(pinCount);

  const terminals = [];
  // Left side pins
  for (let i = 0; i < half; i++) {
    const py = pinY(i, half, bodyY);
    const pinName = pins[i] || `p${i + 1}`;
    terminals.push({ name: pinName, x: 0, y: py });
  }
  // Right side pins (bottom-right first = pin half+1, top-right last = pin pinCount)
  for (let i = 0; i < half; i++) {
    const py = pinY(half - 1 - i, half, bodyY);
    const pinNum = half + 1 + i;
    const pinName = pins[pinNum - 1] || `p${pinNum}`;
    terminals.push({ name: pinName, x: svgW, y: py });
  }

  return {
    kind,
    w: svgW,
    h: svgH,
    terminals,
    variants: null,
    ...(chip._note ? { _note: chip._note } : {}),
  };
}

// ── Pin maps for all DIP logic ICs ──────────────────────────────────
// Pin names in order: pin1, pin2, ..., pinN (standard DIP numbering)

const PIN_MAPS = [
  // 14-pin 74HC family
  {
    kind: '74hc00', pinCount: 14, label: '74HC00', sublabel: 'QUAD NAND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc02', pinCount: 14, label: '74HC02', sublabel: 'QUAD NOR',
    pins: ['1y','1a','1b','2y','2a','2b','gnd', '3a','3b','3y','4a','4b','4y','vcc'],
  },
  {
    kind: '74hc04', pinCount: 14, label: '74HC04', sublabel: 'HEX INV',
    pins: ['1a','1y','2a','2y','3a','3y','gnd', '4y','4a','5y','5a','6y','6a','vcc'],
  },
  {
    kind: '74hc08', pinCount: 14, label: '74HC08', sublabel: 'QUAD AND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc10', pinCount: 14, label: '74HC10', sublabel: 'TRI NAND3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc11', pinCount: 14, label: '74HC11', sublabel: 'TRI AND3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc14', pinCount: 14, label: '74HC14', sublabel: 'HEX SCHMITT',
    pins: ['1a','1y','2a','2y','3a','3y','gnd', '4y','4a','5y','5a','6y','6a','vcc'],
  },
  {
    kind: '74hc20', pinCount: 14, label: '74HC20', sublabel: 'DUAL NAND4',
    pins: ['1a','1b','nc1','1c','1d','1y','gnd', '2y','2a','2b','nc2','2c','2d','vcc'],
  },
  {
    kind: '74hc21', pinCount: 14, label: '74HC21', sublabel: 'DUAL AND4',
    pins: ['1a','1b','nc1','1c','1d','1y','gnd', '2y','2a','2b','nc2','2c','2d','vcc'],
  },
  {
    kind: '74hc27', pinCount: 14, label: '74HC27', sublabel: 'TRI NOR3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc32', pinCount: 14, label: '74HC32', sublabel: 'QUAD OR',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc73', pinCount: 14, label: '74HC73', sublabel: 'DUAL JK-FF',
    pins: ['1clk','1clr','1k','vcc','2clk','2clr','2k', '2q','2qn','2j','gnd','1q','1qn','1j'],
  },
  {
    kind: '74hc74', pinCount: 14, label: '74HC74', sublabel: 'DUAL D-FF',
    pins: ['1clr','1d','1clk','1pre','1q','1qn','gnd', '2qn','2q','2pre','2clk','2d','2clr','vcc'],
  },
  {
    kind: '74hc86', pinCount: 14, label: '74HC86', sublabel: 'QUAD XOR',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc93', pinCount: 14, label: '74HC93', sublabel: '4-BIT CTR',
    pins: ['cka','nc1','nc2','nc3','vcc','r0a','r0b', 'qd','qc','gnd','qb','qa','nc4','ckb'],
  },
  {
    kind: '74hc95', pinCount: 14, label: '74HC95', sublabel: '4-BIT SHFT',
    pins: ['ser','a','b','c','d','mode','gnd', 'clk','qd','qc','qb','qa','nc','vcc'],
  },
  {
    kind: '74hc132', pinCount: 14, label: '74HC132', sublabel: 'SCHMITT NAND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  // 16-pin chips
  {
    kind: 'cd4017', pinCount: 16, label: 'CD4017', sublabel: 'DECADE CTR',
    pins: ['q5','q1','q0','q2','q6','q7','q3','gnd', 'q8','q4','q9','co','en','clk','rst','vcc'],
  },
  {
    kind: 'cd4511', pinCount: 16, label: 'CD4511', sublabel: 'BCD-7SEG',
    pins: ['b','c','lt','bi','le','d','a','gnd', 'e','d_out','c_out','b_out','a_out','g','f','vcc'],
  },
  {
    kind: '74hc595', pinCount: 16, label: '74HC595', sublabel: 'SHIFT REG',
    pins: ['qb','qc','qd','qe','qf','qg','qh','gnd', 'qh_s','srclr','srclk','rclk','oe','ser','qa','vcc'],
  },
  // ── L293D: TI L293D datasheet (SLRS008) — 16-pin H-bridge motor driver
  // The four GND pins (4,5,12,13) are heat-sink pads, not just signal ground.
  {
    kind: 'l293d', pinCount: 16, label: 'L293D', sublabel: 'H-BRIDGE',
    pins: ['en1','in1','out1','gnd1','gnd2','out2','in2','vcc2', 'en2','in3','out3','gnd3','gnd4','out4','in4','vcc1'],
  },
  // ── Added from Tinkercad gap analysis, pin maps from datasheets ───
  // 74HC75: TI SN74HC75 datasheet (SCLS154) — 16-pin quad bistable latch
  {
    kind: '74hc75', pinCount: 16, label: '74HC75', sublabel: 'QUAD LATCH',
    pins: ['1q','1qn','1d','3_4e','vcc','3d','3qn','3q', '4q','4qn','4d','gnd','1_2e','2d','2qn','2q'],
  },
  // 74HC283: TI SN74HC283 datasheet (SCLS108) — 16-pin 4-bit adder
  {
    kind: '74hc283', pinCount: 16, label: '74HC283', sublabel: '4-BIT ADDER',
    pins: ['s2','b2','a2','s1','a1','b1','cin','gnd', 'cout','s4','b4','a4','s3','a3','b3','vcc'],
  },
  // PCF8574: NXP PCF8574 datasheet (Rev 5) — 16-pin I2C I/O expander
  {
    kind: 'pcf8574', pinCount: 16, label: 'PCF8574', sublabel: 'I2C EXPAND',
    pins: ['a0','a1','a2','p0','p1','p2','p3','vss', 'p4','p5','p6','p7','int','scl','sda','vdd'],
  },
  // ── STC12C5A60S2: 40-pin DIP ────────────────────────────────────
  // Pin map from stc/docs/PINOUT.md (sourced from official STC12C5A60S2
  // datasheet, rev 2011-07-15). Uses PORT NAMES, not generic 8051
  // functional aliases — that exact trap is documented in the lab notes.
  // P0 runs DESCENDING: pin 32=P0.7, pin 39=P0.0.
  {
    kind: 'stc_mcu', pinCount: 40, label: 'STC12', sublabel: 'C5A60S2',
    pins: [
      'P1.0','P1.1','P1.2','P1.3','P1.4','P1.5','P1.6','P1.7',  // 1-8
      'RST','P3.0','P3.1','P3.2','P3.3','P3.4','P3.5','P3.6',   // 9-16
      'P3.7','XTAL2','XTAL1','GND',                               // 17-20
      'P2.0','P2.1','P2.2','P2.3','P2.4','P2.5','P2.6','P2.7',  // 21-28
      'P4.4','P4.5','P4.6','P0.7','P0.6','P0.5','P0.4','P0.3',  // 29-36
      'P0.2','P0.1','P0.0','VCC',                                 // 37-40
    ],
  },
  // ── NE556 Dual Timer: 14-pin DIP ─────────────────────────────────
  // Pin map from TI NE556 datasheet (SLFS023)
  {
    kind: '556', pinCount: 14, label: 'NE556', sublabel: 'DUAL TIMER',
    pins: ['1dis','1thr','1ctl','1rst','1out','1trg','gnd', '2trg','2out','2rst','2ctl','2thr','2dis','vcc'],
  },
  // ── LM393 Dual Comparator: 8-pin DIP ─────────────────────────────
  // Pin map from TI LM393 datasheet (SLCS007)
  {
    kind: 'lm393', pinCount: 8, label: 'LM393', sublabel: 'DUAL COMP',
    pins: ['1out','1inp','1inn','gnd', '2inn','2inp','2out','vcc'],
  },
  // ── LM339 Quad Comparator: 14-pin DIP ────────────────────────────
  // Pin map from TI LM339 datasheet (SLCS006)
  {
    kind: 'lm339', pinCount: 14, label: 'LM339', sublabel: 'QUAD COMP',
    pins: ['2out','3out','vcc','4inn','4inp','4out','gnd', '1out','1inp','1inn','2inn','2inp','3inn','3inp'],
  },
  // ── ATtiny85: 8-pin DIP ───────────────────────────────────────────
  // Pin map from Microchip ATtiny85 datasheet.
  // Tinkercad does not confirm it is ATtiny85 specifically (unverified).
  {
    kind: 'attiny85', pinCount: 8, label: 'ATtiny85', sublabel: 'unverified',
    pins: ['pb5','pb3','pb4','gnd', 'pb0','pb1','pb2','vcc'],
    _note: 'Tinkercad shows an 8-pin ATtiny but does not name the variant. ATtiny85 assumed (most common). Could be ATtiny45 or ATtiny25.',
  },

  // ── Intel 8086-family support chips (for the bw-board E6 8086 tier) ──
  // Terminal names are the ones bw-board/src/i8086-extract.js reads BY NAME
  // (csb, a0, a1, cd, mio); a chip whose select or register lines are
  // misnamed or miswired extracts to a named refusal instead of a machine.

  // Intel 8255A PPI. DIP-40. Pinout audited against the Intel 8255A
  // datasheet: PA0-3 pins 1-4, PA4-7 pins 37-40, PB0-7 pins 18-25, PC0-3
  // pins 14-17, PC4-7 pins 10-13, /RD pin 5, /CS pin 6, A1 pin 8, A0 pin 9,
  // Vcc pin 26, GND pin 7, D0-7 pins 34-27, RESET pin 35, /WR pin 36.
  {
    kind: 'i8255', pinCount: 40, label: '8255', sublabel: 'PPI',
    pins: [
      'pa3','pa2','pa1','pa0','rdb','csb','gnd','a1','a0','pc7',   // 1-10
      'pc6','pc5','pc4','pc0','pc1','pc2','pc3','pb0','pb1','pb2', // 11-20
      'pb3','pb4','pb5','pb6','pb7','vcc','d7','d6','d5','d4',     // 21-30
      'd3','d2','d1','d0','reset','wrb','pa4','pa5','pa6','pa7',   // 31-40
    ],
    _note: 'Intel 8255A Programmable Peripheral Interface. DIP-40. Extractor reads csb (pin 6), a0 (pin 9), a1 (pin 8). Three 8-bit ports PA/PB/PC; port C is two independently-directioned nibbles. /RD pin 5, /WR pin 36, RESET pin 35 (active HIGH). Pinout audited against Intel 8255A datasheet.',
  },

  // Intel 8254 PIT. DIP-24. D7-D0 pins 1-8, CLK0/OUT0/GATE0 pins 9-11,
  // GND pin 12, OUT1/GATE1/CLK1 pins 13-15, GATE2/OUT2/CLK2 pins 16-18,
  // A0 pin 19, A1 pin 20, /CS pin 21, /RD pin 22, /WR pin 23, Vcc pin 24.
  {
    kind: 'i8254', pinCount: 24, label: '8254', sublabel: 'PIT',
    pins: [
      'd7','d6','d5','d4','d3','d2','d1','d0','clk0','out0',       // 1-10
      'gate0','gnd','out1','gate1','clk1','gate2','out2','clk2','a0','a1', // 11-20
      'csb','rdb','wrb','vcc',                                     // 21-24
    ],
    _note: 'Intel 8254 Programmable Interval Timer. DIP-24. Extractor reads csb (pin 21), a0 (pin 19), a1 (pin 20). Three 16-bit counters, each with clk/gate/out. Pinout audited against Intel 8254 datasheet (order 231164).',
  },
  {
    kind: 'i8253', pinCount: 24, label: '8253', sublabel: 'PIT',
    pins: [
      'd7','d6','d5','d4','d3','d2','d1','d0','clk0','out0',       // 1-10
      'gate0','gnd','out1','gate1','clk1','gate2','out2','clk2','a0','a1', // 11-20
      'csb','rdb','wrb','vcc',                                     // 21-24
    ],
    _note: 'Intel 8253 Programmable Interval Timer — the earlier, pin-identical part the original IBM PC/XT used; it lacks the 8254 read-back command (the extractor emits variant:8253 so the model refuses it). DIP-24, same bond-out as the 8254. Pinout audited against Intel 8253 datasheet.',
  },

  // Intel 8259A PIC. DIP-28. /CS pin 1, /WR pin 2, /RD pin 3, D7-D0 pins
  // 4-11, CAS0-2 pins 12-14, GND pin 15, /SP-EN pin 16, INT pin 17,
  // IR7-IR0 pins 18-25, A0 pin 26, /INTA pin 27, Vcc pin 28.
  {
    kind: 'i8259', pinCount: 28, label: '8259', sublabel: 'PIC',
    pins: [
      'csb','wrb','rdb','d7','d6','d5','d4','d3','d2','d1',        // 1-10
      'd0','cas0','cas1','cas2','gnd','sp_enb','intr','ir7','ir6','ir5', // 11-20
      'ir4','ir3','ir2','ir1','ir0','a0','intab','vcc',           // 21-28
    ],
    _note: 'Intel 8259A Programmable Interrupt Controller. DIP-28. Extractor reads csb (pin 1), a0 (pin 26). Eight IR inputs, INT out (to the CPU intr pin), /INTA in. Pinout audited against Intel 8259A datasheet.',
  },

  // Intel 8251A USART. DIP-28. D2 pin 1, D3 pin 2, RxD pin 3, GND pin 4,
  // D4-D7 pins 5-8, TxC pin 9, /WR pin 10, /CS pin 11, C/D pin 12, /RD
  // pin 13, RxRDY pin 14, TxRDY pin 15, SYNDET pin 16, /CTS pin 17,
  // TxEMPTY pin 18, TxD pin 19, CLK pin 20, RESET pin 21, /DSR pin 22,
  // /RTS pin 23, /DTR pin 24, RxC pin 25, Vcc pin 26, D0 pin 27, D1 pin 28.
  {
    kind: 'i8251', pinCount: 28, label: '8251', sublabel: 'USART',
    pins: [
      'd2','d3','rxd','gnd','d4','d5','d6','d7','txc','wrb',       // 1-10
      'csb','cd','rdb','rxrdy','txrdy','syndet','ctsb','txempty','txd','clk', // 11-20
      'reset','dsrb','rtsb','dtrb','rxc','vcc','d0','d1',          // 21-28
    ],
    _note: 'Intel 8251A USART. DIP-28. Extractor reads csb (pin 11), cd (C/D#, pin 12). C/D# selects data vs control/status. Data bus is scattered: D0 pin 27, D1 pin 28, D2 pin 1, D3 pin 2, D4-D7 pins 5-8. Pinout audited against Intel 8251A datasheet.',
  },

  // Intel 8284A clock generator. DIP-18. Drawable only — the extractor does
  // not decode it (it carries no registers); it provides CLK/RESET/READY to
  // the CPU. CSYNC pin 1, PCLK pin 2, /AEN1 pin 3, RDY1 pin 4, READY pin 5,
  // RDY2 pin 6, /AEN2 pin 7, CLK pin 8, GND pin 9, F/C pin 10, EFI pin 11,
  // /ASYNC pin 12, /RES pin 13, RESET pin 14, OSC pin 15, X2 pin 16,
  // X1 pin 17, Vcc pin 18.
  {
    kind: 'i8284', pinCount: 18, label: '8284', sublabel: 'CLK GEN',
    pins: [
      'csync','pclk','aen1b','rdy1','ready','rdy2','aen2b','clk','gnd',  // 1-9
      'fcb','efi','asyncb','resb','reset','osc','x2','x1','vcc',         // 10-18
    ],
    _note: 'Intel 8284A clock generator. DIP-18. Drawable only; the extractor does not decode it. Divides the crystal by three to CLK, and synchronises RESET and READY for the CPU. Pinout audited against Intel 8284A datasheet.',
  },

  // Intel 8086 CPU. DIP-40. SIMPLIFIED TEACHING PART: the real 8086
  // multiplexes AD0-AD15 and A16/S3-A19/S6, valid only while ALE is high,
  // and a real build latches them through a 74LS373. This part presents the
  // DE-MULTIPLEXED address a0-a19 directly — the same clean-address
  // simplification the 6502 and Z80 parts make — because a first breadboard
  // lesson wires the address decode and M/IO, which are identical for both,
  // and the extractor reads only a0-a19 and mio. The ALE-latched realism is
  // a separate roadmap lesson, not modelled here.
  {
    kind: 'i8086', pinCount: 40, label: '8086', sublabel: 'CPU',
    pins: [
      'a0','a1','a2','a3','a4','a5','a6','a7','a8','a9',           // 1-10
      'a10','a11','a12','a13','a14','a15','a16','a17','a18','a19', // 11-20
      'd0','d1','d2','d3','d4','d5','d6','d7','mio','rdb',         // 21-30
      'wrb','ale','clk','reset','ready','intr','nmi','intab','gnd','vcc', // 31-40
    ],
    _note: 'Intel 8086 CPU. DIP-40. SIMPLIFIED TEACHING PART presenting de-multiplexed address a0-a19 and M/IO# (mio) — the extractor reads exactly these. The real 8086 multiplexes AD0-AD15/A16-A19 behind ALE and needs a 74LS373 latch; that realism is a bw-board E6 roadmap lesson, not this part. d0-d7 shown as the wiring data stub.',
  },

  // Intel 8088 CPU. Same de-multiplexed teaching layout as the 8086 (the
  // extractor treats them identically — it reads a0-a19 and mio, and the
  // 8-bit vs 16-bit data bus does not affect address decode).
  {
    kind: 'i8088', pinCount: 40, label: '8088', sublabel: 'CPU',
    pins: [
      'a0','a1','a2','a3','a4','a5','a6','a7','a8','a9',           // 1-10
      'a10','a11','a12','a13','a14','a15','a16','a17','a18','a19', // 11-20
      'd0','d1','d2','d3','d4','d5','d6','d7','mio','rdb',         // 21-30
      'wrb','ale','clk','reset','ready','intr','nmi','intab','gnd','vcc', // 31-40
    ],
    _note: 'Intel 8088 CPU (8-bit external bus). DIP-40. SIMPLIFIED TEACHING PART, same de-multiplexed a0-a19 + mio layout as the 8086 part — the extractor reads a0-a19 and mio and treats the two identically. The Tier A reference build (TIERA8088) uses this CPU.',
  },
];

// ── Main ────────────────────────────────────────────────────────────
function generate(chip) {
  const svgContent = generateSvg(chip);
  const jsonContent = generateJson(chip);

  const svgPath = path.join(PARTS_DIR, `${chip.kind}.svg`);
  const jsonPath = path.join(PARTS_DIR, `${chip.kind}.json`);

  fs.writeFileSync(svgPath, svgContent);
  fs.writeFileSync(jsonPath, JSON.stringify(jsonContent, null, 2) + '\n');
  console.log(`  ${chip.kind} (${chip.pinCount}-pin): ${svgPath}`);
}

const target = process.argv[2];
if (target) {
  const chip = PIN_MAPS.find(c => c.kind === target);
  if (!chip) {
    console.error(`Unknown chip: ${target}. Available: ${PIN_MAPS.map(c => c.kind).join(', ')}`);
    process.exit(1);
  }
  generate(chip);
} else {
  console.log(`Generating ${PIN_MAPS.length} DIP ICs...`);
  for (const chip of PIN_MAPS) {
    generate(chip);
  }
  console.log(`Done. ${PIN_MAPS.length} chips generated.`);
}
