#!/usr/bin/env node
/**
 * generate-dip.js — Parametric DIP IC SVG + JSON sidecar generator.
 *
 * Given a pin-map table (chip kind, pin count, pin names, label),
 * generates bench-style DIP package SVGs and matching JSON sidecars
 * in parts/<kind>.svg and parts/<kind>.json.
 *
 * DIP geometry:
 *   Pin 1 is top-left, numbering goes DOWN the left side then
 *   UP the right side (standard DIP convention).
 *   VCC is typically the top-right pin, GND the bottom-left.
 *
 * Usage: node generate-dip.js          (generates all chips in PIN_MAPS)
 *        node generate-dip.js 74hc00   (generates one chip)
 */

const fs = require('fs');
const path = require('path');

const PARTS_DIR = path.join(__dirname, 'parts');

// ── DIP geometry constants ──────────────────────────────────────────
const PIN_SPACING = 5;       // vertical spacing between pins
const PIN_LENGTH  = 10;      // lead wire length from body edge
const BODY_X      = 10;      // left edge of IC body
const BODY_RX     = 2;       // corner radius
const PAD_R       = 1.5;     // terminal pad radius
const PIN_STROKE  = 1.5;
const NOTCH_R     = 3;       // notch semicircle radius
const DOT_R       = 1.5;    // pin-1 dot radius

function dipGeometry(pinCount) {
  const half = pinCount / 2;
  const bodyH = (half - 1) * PIN_SPACING + 12;  // padding top/bottom
  const bodyW = pinCount > 20 ? 60 : 50;        // wider body for DIP-40+
  const svgW  = bodyW + 2 * BODY_X;
  const svgH  = bodyH + 4;  // small margin
  const bodyY = 2;
  return { half, bodyH, bodyW, svgW, svgH, bodyY };
}

function pinY(index, half, bodyY) {
  // index 0 = pin 1 (top-left), index half-1 = bottom-left
  const topPad = 6;
  return bodyY + topPad + index * PIN_SPACING;
}

// ── SVG generation ──────────────────────────────────────────────────
function generateSvg(chip) {
  const { kind, pinCount, pins, label, sublabel } = chip;
  const { half, bodyH, bodyW, svgW, svgH, bodyY } = dipGeometry(pinCount);
  const bodyRight = BODY_X + bodyW;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${svgW} ${svgH}" width="${svgW}" height="${svgH}">\n`;
  svg += `  <!-- ${label} — ${pinCount}-pin DIP, generated by generate-dip.js -->\n`;

  // Body
  svg += `  <rect x="${BODY_X}" y="${bodyY}" width="${bodyW}" height="${bodyH}" rx="${BODY_RX}" fill="#303030" stroke="#1a1a1a" stroke-width="1"/>\n`;

  // Notch at top center
  const notchCx = BODY_X + bodyW / 2;
  svg += `  <path d="M${notchCx - NOTCH_R} ${bodyY} A${NOTCH_R} ${NOTCH_R} 0 0 1 ${notchCx + NOTCH_R} ${bodyY}" fill="#303030" stroke="#555" stroke-width="0.8"/>\n`;

  // Pin 1 dot
  const dotX = BODY_X + 5;
  const dotY = bodyY + 5;
  svg += `  <circle cx="${dotX}" cy="${dotY}" r="${DOT_R}" fill="#b0b0b0"/>\n`;

  // Label
  const labelY = bodyY + bodyH / 2 - 1;
  svg += `  <text x="${BODY_X + bodyW / 2}" y="${labelY}" text-anchor="middle" font-family="monospace" font-size="5.5" fill="#c0c0c0">${label}</text>\n`;
  if (sublabel) {
    svg += `  <text x="${BODY_X + bodyW / 2}" y="${labelY + 8}" text-anchor="middle" font-family="monospace" font-size="3.5" fill="#888">${sublabel}</text>\n`;
  }

  // Pins — left side (pin 1 to pin half)
  for (let i = 0; i < half; i++) {
    const py = pinY(i, half, bodyY);
    const pinNum = i + 1;
    const pinName = pins[i] || `p${pinNum}`;
    // Lead wire
    svg += `  <line x1="0" y1="${py}" x2="${BODY_X}" y2="${py}" stroke="#aaa" stroke-width="${PIN_STROKE}" stroke-linecap="round"/>\n`;
    // Pad
    svg += `  <circle cx="0" cy="${py}" r="${PAD_R}" fill="#c0c0c0"/>\n`;
    // Pin label (inside body, near left edge)
    const labelFontSize = pinName.length > 4 ? 2.5 : 3;
    svg += `  <text x="${BODY_X + 3}" y="${py + 1}" font-family="monospace" font-size="${labelFontSize}" fill="#888">${pinName}</text>\n`;
  }

  // Pins — right side (pin pinCount down to pin half+1)
  for (let i = 0; i < half; i++) {
    const py = pinY(half - 1 - i, half, bodyY);  // mirrored: top-right is highest pin number
    const pinNum = half + 1 + i;
    const pinName = pins[pinNum - 1] || `p${pinNum}`;
    // Lead wire
    svg += `  <line x1="${bodyRight}" y1="${py}" x2="${svgW}" y2="${py}" stroke="#aaa" stroke-width="${PIN_STROKE}" stroke-linecap="round"/>\n`;
    // Pad
    svg += `  <circle cx="${svgW}" cy="${py}" r="${PAD_R}" fill="#c0c0c0"/>\n`;
    // Pin label (inside body, near right edge)
    const labelFontSize = pinName.length > 4 ? 2.5 : 3;
    svg += `  <text x="${bodyRight - 3}" y="${py + 1}" text-anchor="end" font-family="monospace" font-size="${labelFontSize}" fill="#888">${pinName}</text>\n`;
  }

  svg += `</svg>\n`;
  return svg;
}

// ── JSON sidecar generation ─────────────────────────────────────────
function generateJson(chip) {
  const { kind, pinCount, pins } = chip;
  const { half, svgW, svgH, bodyY } = dipGeometry(pinCount);

  const terminals = [];
  // Left side pins
  for (let i = 0; i < half; i++) {
    const py = pinY(i, half, bodyY);
    const pinName = pins[i] || `p${i + 1}`;
    terminals.push({ name: pinName, x: 0, y: py });
  }
  // Right side pins (bottom-right first = pin half+1, top-right last = pin pinCount)
  for (let i = 0; i < half; i++) {
    const py = pinY(half - 1 - i, half, bodyY);
    const pinNum = half + 1 + i;
    const pinName = pins[pinNum - 1] || `p${pinNum}`;
    terminals.push({ name: pinName, x: svgW, y: py });
  }

  return {
    kind,
    w: svgW,
    h: svgH,
    terminals,
    variants: null,
  };
}

// ── Pin maps for all DIP logic ICs ──────────────────────────────────
// Pin names in order: pin1, pin2, ..., pinN (standard DIP numbering)

const PIN_MAPS = [
  // 14-pin 74HC family
  {
    kind: '74hc00', pinCount: 14, label: '74HC00', sublabel: 'QUAD NAND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc02', pinCount: 14, label: '74HC02', sublabel: 'QUAD NOR',
    pins: ['1y','1a','1b','2y','2a','2b','gnd', '3a','3b','3y','4a','4b','4y','vcc'],
  },
  {
    kind: '74hc04', pinCount: 14, label: '74HC04', sublabel: 'HEX INV',
    pins: ['1a','1y','2a','2y','3a','3y','gnd', '4y','4a','5y','5a','6y','6a','vcc'],
  },
  {
    kind: '74hc08', pinCount: 14, label: '74HC08', sublabel: 'QUAD AND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc10', pinCount: 14, label: '74HC10', sublabel: 'TRI NAND3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc11', pinCount: 14, label: '74HC11', sublabel: 'TRI AND3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc14', pinCount: 14, label: '74HC14', sublabel: 'HEX SCHMITT',
    pins: ['1a','1y','2a','2y','3a','3y','gnd', '4y','4a','5y','5a','6y','6a','vcc'],
  },
  {
    kind: '74hc20', pinCount: 14, label: '74HC20', sublabel: 'DUAL NAND4',
    pins: ['1a','1b','nc1','1c','1d','1y','gnd', '2y','2a','2b','nc2','2c','2d','vcc'],
  },
  {
    kind: '74hc21', pinCount: 14, label: '74HC21', sublabel: 'DUAL AND4',
    pins: ['1a','1b','nc1','1c','1d','1y','gnd', '2y','2a','2b','nc2','2c','2d','vcc'],
  },
  {
    kind: '74hc27', pinCount: 14, label: '74HC27', sublabel: 'TRI NOR3',
    pins: ['1a','1b','2a','2b','2c','2y','gnd', '3y','3a','3b','3c','1y','1c','vcc'],
  },
  {
    kind: '74hc32', pinCount: 14, label: '74HC32', sublabel: 'QUAD OR',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc73', pinCount: 14, label: '74HC73', sublabel: 'DUAL JK-FF',
    pins: ['1clk','1clr','1k','vcc','2clk','2clr','2k', '2q','2qn','2j','gnd','1q','1qn','1j'],
  },
  {
    kind: '74hc74', pinCount: 14, label: '74HC74', sublabel: 'DUAL D-FF',
    pins: ['1clr','1d','1clk','1pre','1q','1qn','gnd', '2qn','2q','2pre','2clk','2d','2clr','vcc'],
  },
  {
    kind: '74hc86', pinCount: 14, label: '74HC86', sublabel: 'QUAD XOR',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  {
    kind: '74hc93', pinCount: 14, label: '74HC93', sublabel: '4-BIT CTR',
    pins: ['cka','nc1','nc2','nc3','vcc','r0a','r0b', 'qd','qc','gnd','qb','qa','nc4','ckb'],
  },
  {
    kind: '74hc95', pinCount: 14, label: '74HC95', sublabel: '4-BIT SHFT',
    pins: ['ser','a','b','c','d','mode','gnd', 'clk','qd','qc','qb','qa','nc','vcc'],
  },
  {
    kind: '74hc132', pinCount: 14, label: '74HC132', sublabel: 'SCHMITT NAND',
    pins: ['1a','1b','1y','2a','2b','2y','gnd', '3y','3a','3b','4y','4a','4b','vcc'],
  },
  // 16-pin chips
  {
    kind: 'cd4017', pinCount: 16, label: 'CD4017', sublabel: 'DECADE CTR',
    pins: ['q5','q1','q0','q2','q6','q7','q3','gnd', 'q8','q4','q9','co','en','clk','rst','vcc'],
  },
  {
    kind: 'cd4511', pinCount: 16, label: 'CD4511', sublabel: 'BCD-7SEG',
    pins: ['b','c','lt','bi','le','d','a','gnd', 'e','d_out','c_out','b_out','a_out','g','f','vcc'],
  },
  {
    kind: '74hc595', pinCount: 16, label: '74HC595', sublabel: 'SHIFT REG',
    pins: ['qb','qc','qd','qe','qf','qg','qh','gnd', 'qh_s','srclr','srclk','rclk','oe','ser','qa','vcc'],
  },
  // ── Added from Tinkercad gap analysis, pin maps from datasheets ───
  // 74HC75: TI SN74HC75 datasheet (SCLS154) — 16-pin quad bistable latch
  {
    kind: '74hc75', pinCount: 16, label: '74HC75', sublabel: 'QUAD LATCH',
    pins: ['1q','1qn','1d','3_4e','vcc','3d','3qn','3q', '4q','4qn','4d','gnd','1_2e','2d','2qn','2q'],
  },
  // 74HC283: TI SN74HC283 datasheet (SCLS108) — 16-pin 4-bit adder
  {
    kind: '74hc283', pinCount: 16, label: '74HC283', sublabel: '4-BIT ADDER',
    pins: ['s2','b2','a2','s1','a1','b1','cin','gnd', 'cout','s4','b4','a4','s3','a3','b3','vcc'],
  },
  // PCF8574: NXP PCF8574 datasheet (Rev 5) — 16-pin I2C I/O expander
  {
    kind: 'pcf8574', pinCount: 16, label: 'PCF8574', sublabel: 'I2C EXPAND',
    pins: ['a0','a1','a2','p0','p1','p2','p3','vss', 'p4','p5','p6','p7','int','scl','sda','vdd'],
  },
  // ── STC12C5A60S2: 40-pin DIP, 8051-compatible ────────────────────
  // Pin map from STC12C5A60S2 datasheet (STC Micro), 8051-standard
  // pinout with STC extensions on P4. Pins 1-20 left, 21-40 right.
  {
    kind: 'stc_mcu', pinCount: 40, label: 'STC12', sublabel: 'C5A60S2',
    pins: [
      'p1.0','p1.1','p1.2','p1.3','p1.4','p1.5','p1.6','p1.7',  // 1-8
      'rst','rxd','txd','int0','int1','t0','t1','wr',            // 9-16
      'rd','xtal2','xtal1','gnd',                                 // 17-20
      'p2.0','p2.1','p2.2','p2.3','p2.4','p2.5','p2.6','p2.7',  // 21-28
      'psen','ale','ea','p0.7','p0.6','p0.5','p0.4','p0.3',      // 29-32, 33-36
      'p0.2','p0.1','p0.0','vcc',                                // 37-40
    ],
  },
  // ── NE556 Dual Timer: 14-pin DIP ─────────────────────────────────
  // Pin map from TI NE556 datasheet (SLFS023)
  {
    kind: '556', pinCount: 14, label: 'NE556', sublabel: 'DUAL TIMER',
    pins: ['1dis','1thr','1ctl','1rst','1out','1trg','gnd', '2trg','2out','2rst','2ctl','2thr','2dis','vcc'],
  },
  // ── LM393 Dual Comparator: 8-pin DIP ─────────────────────────────
  // Pin map from TI LM393 datasheet (SLCS007)
  {
    kind: 'lm393', pinCount: 8, label: 'LM393', sublabel: 'DUAL COMP',
    pins: ['1out','1inp','1inn','gnd', '2inn','2inp','2out','vcc'],
  },
  // ── LM339 Quad Comparator: 14-pin DIP ────────────────────────────
  // Pin map from TI LM339 datasheet (SLCS006)
  {
    kind: 'lm339', pinCount: 14, label: 'LM339', sublabel: 'QUAD COMP',
    pins: ['2out','3out','vcc','4inn','4inp','4out','gnd', '1out','1inp','1inn','2inn','2inp','3inn','3inp'],
  },
  // ── ATtiny85: 8-pin DIP ───────────────────────────────────────────
  // Pin map from Microchip ATtiny85 datasheet.
  // Tinkercad does not confirm it is ATtiny85 specifically (unverified).
  {
    kind: 'attiny85', pinCount: 8, label: 'ATtiny85', sublabel: 'unverified',
    pins: ['pb5','pb3','pb4','gnd', 'pb0','pb1','pb2','vcc'],
    _note: 'Tinkercad shows an 8-pin ATtiny but does not name the variant. ATtiny85 assumed (most common). Could be ATtiny45 or ATtiny25.',
  },
];

// ── Main ────────────────────────────────────────────────────────────
function generate(chip) {
  const svgContent = generateSvg(chip);
  const jsonContent = generateJson(chip);

  const svgPath = path.join(PARTS_DIR, `${chip.kind}.svg`);
  const jsonPath = path.join(PARTS_DIR, `${chip.kind}.json`);

  fs.writeFileSync(svgPath, svgContent);
  fs.writeFileSync(jsonPath, JSON.stringify(jsonContent, null, 2) + '\n');
  console.log(`  ${chip.kind} (${chip.pinCount}-pin): ${svgPath}`);
}

const target = process.argv[2];
if (target) {
  const chip = PIN_MAPS.find(c => c.kind === target);
  if (!chip) {
    console.error(`Unknown chip: ${target}. Available: ${PIN_MAPS.map(c => c.kind).join(', ')}`);
    process.exit(1);
  }
  generate(chip);
} else {
  console.log(`Generating ${PIN_MAPS.length} DIP ICs...`);
  for (const chip of PIN_MAPS) {
    generate(chip);
  }
  console.log(`Done. ${PIN_MAPS.length} chips generated.`);
}
