#!/usr/bin/env node
/**
 * generate-dip-art.js — SVG for a DIP sidecar that already exists.
 *
 * generate-dip.js owns the parts it defines in PIN_MAPS and writes BOTH
 * halves from that table. Sidecars that arrived another way — upstreamed
 * from bw-circuit-ui, hand-written — have no PIN_MAPS entry, so running
 * that generator would either skip them or overwrite a tracked JSON with a
 * table it was never derived from. This reads the JSON as the authority and
 * emits only the missing half, so the pads land exactly on the terminal
 * coordinates the sidecar already publishes.
 *
 * Left pins are x == 0, right pins are x == w; everything else is a pin this
 * script cannot place and is reported rather than guessed.
 *
 * Usage: node generate-dip-art.js 74hc125 [74hc34 ...]
 *        node generate-dip-art.js --all      (every JSON with no SVG)
 */

const fs = require('fs');
const path = require('path');

const PARTS_DIR = path.join(__dirname, 'parts');
const BODY_INSET = 10;   // lead length; body spans BODY_INSET..w-BODY_INSET
const PAD_R = 1.5;

/** Short subtitle under the part number. Falls back to nothing. */
const SUBTITLES = {
  '74hc125': 'QUAD 3-ST BUF',
  '74hc34': 'HEX BUFFER',
  '74hc4050': 'HEX BUF/LVL',
};

function art(kind, sc) {
  const { w, h } = sc;
  const bodyX = BODY_INSET;
  const bodyW = w - 2 * BODY_INSET;
  const midX = w / 2;
  const label = kind.toUpperCase();
  const sub = SUBTITLES[kind] || '';

  const out = [];
  out.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">`);
  out.push(`  <!-- ${label} — ${sc.terminals.length}-pin DIP, generated by generate-dip-art.js from ${kind}.json -->`);
  out.push(`  <rect x="${bodyX}" y="2" width="${bodyW}" height="${h - 4}" rx="2" fill="#303030" stroke="#1a1a1a" stroke-width="1"/>`);
  out.push(`  <path d="M${midX - 3} 2 A3 3 0 0 1 ${midX + 3} 2" fill="#303030" stroke="#555" stroke-width="0.8"/>`);
  out.push(`  <circle cx="${bodyX + 5}" cy="7" r="1.5" fill="#b0b0b0"/>`);
  out.push(`  <text x="${midX}" y="${h / 2 - 1}" text-anchor="middle" font-family="monospace" font-size="5.5" fill="#c0c0c0">${label}</text>`);
  if (sub) {
    out.push(`  <text x="${midX}" y="${h / 2 + 7}" text-anchor="middle" font-family="monospace" font-size="3.5" fill="#888">${sub}</text>`);
  }

  const unplaceable = [];
  for (const t of sc.terminals) {
    const { name, x, y } = t;
    if (x === 0) {
      out.push(`  <line x1="0" y1="${y}" x2="${bodyX}" y2="${y}" stroke="#aaa" stroke-width="1.5" stroke-linecap="round"/>`);
      out.push(`  <circle cx="0" cy="${y}" r="${PAD_R}" fill="#c0c0c0"/>`);
      out.push(`  <text x="${bodyX + 3}" y="${y + 1}" font-family="monospace" font-size="3" fill="#888">${name}</text>`);
    } else if (x === w) {
      out.push(`  <line x1="${w - bodyX}" y1="${y}" x2="${w}" y2="${y}" stroke="#aaa" stroke-width="1.5" stroke-linecap="round"/>`);
      out.push(`  <circle cx="${w}" cy="${y}" r="${PAD_R}" fill="#c0c0c0"/>`);
      out.push(`  <text x="${w - bodyX - 3}" y="${y + 1}" text-anchor="end" font-family="monospace" font-size="3" fill="#888">${name}</text>`);
    } else {
      unplaceable.push(`${name} at (${x},${y})`);
    }
  }
  out.push('</svg>');
  return { svg: out.join('\n') + '\n', unplaceable };
}

const args = process.argv.slice(2);
let kinds = args.filter((a) => !a.startsWith('--'));
if (args.includes('--all')) {
  kinds = fs.readdirSync(PARTS_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .filter((k) => !fs.existsSync(path.join(PARTS_DIR, `${k}.svg`)));
}
if (kinds.length === 0) {
  console.error('usage: node generate-dip-art.js <kind>... | --all');
  process.exit(2);
}

let failed = 0;
for (const kind of kinds) {
  const jsonPath = path.join(PARTS_DIR, `${kind}.json`);
  if (!fs.existsSync(jsonPath)) {
    console.error(`SKIP ${kind}: no ${kind}.json`);
    failed++;
    continue;
  }
  const sc = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  const { svg, unplaceable } = art(kind, sc);
  if (unplaceable.length) {
    console.error(`SKIP ${kind}: ${unplaceable.length} pin(s) are not on a DIP edge — ${unplaceable.join(', ')}`);
    failed++;
    continue;
  }
  fs.writeFileSync(path.join(PARTS_DIR, `${kind}.svg`), svg);
  console.log(`wrote parts/${kind}.svg (${sc.terminals.length} pins, ${sc.w}x${sc.h})`);
}
process.exit(failed ? 1 : 0);
